apps/k33/posts/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers
from . import views

urlpatterns = patterns(
    'k33.posts.views',
    url(r'^$', views.index, name='list'),
    url(r'^(\d+)$', views.detail, name='detail'),
    url(r'^new$', views.new, name='new'),
    url(r'^(\d+)/edit$', views.edit, name='edit'),
    url(r'^(\d+)/delete', views.delete, name='delete'),
    url(r'^(\d+)/publish', views.publish, name='publish'),
    url(r'^(\d+)/unpublish', views.unpublish, name='unpublish')
)

urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'k33.views.home', name='home'),
	# url(r'^k33/', include('k33.foo.urls')),

	# Uncomment the admin/doc line below to enable admin documentation:
	# url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
	url(r'^votes/',  include('k33.votes.urls')),
	url(r'^accounts/',  include('k33.accounts.urls', namespace='accounts')),
	url(r'^cooking/',  include('k33.cooking.urls')),
	url(r'^posts/',  include('k33.posts.urls', namespace='posts')),
	url(r'^events/',  include('k33.events.urls', namespace='events')),
	url(r'^comments/',  include('k33.comments.urls')),
	url(r'^materials/',  include('k33.materials.urls')),
    # url(r'^production/',  include('k33.production.urls')),
    url(r'^store/',  include('k33.store.urls')),
    url(r'^bookkeeping/',  include('k33.bookkeeping.urls')),
    url(r'^stream/', include('k33.stream.urls')),
	url(r'^$', 'krishna33.views.index', name='index'),
    url(r'^contact$', 'krishna33.views.contact', name='contact'),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    # TODO
    url(r'^api/',  include('k33.posts.api.urls')),
    url(r'^api/',  include('k33.uploads.api.urls')),
    url(r'^api/',  include('k33.accounts.api.urls')),
    url(r'^api/',  include('k33.partners.api.urls')),
    url(r'^api/production/',  include('k33.production.api.urls')),
    url(r'^api/store/',  include('k33.store.api.urls')),
    url(r'^api/materials/',  include('k33.materials.api.urls')),

    url(r'^api/bookkeeping/',  include('k33.bookkeeping.api.urls')),

)
from django.conf import settings
if settings.DEBUG:
	# static files (images, css, javascript, etc.)
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
		'document_root': settings.MEDIA_ROOT}))

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
<!--	 <link rel="stylesheet" href="style.css" /> -->
    {% load staticfiles %}
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8" />
	<title>{% block page-title %}Официальный сайт общества Сознания Кришны в городе Владимире{% endblock %}</title>
    <meta name="description" content="{% block page-description %}Официальный сайт общества Сознания Кришны в городе Владимире. Контакты, философия, новости."{% endblock %}>
    <meta name="keywords" content="{% block page-keywords %}Харе, Кришна, город Владимир, общество, сознание, кришнаиты, вайшнавы, религия, вайшнавизм, философия, образование{% endblock %}">
    <meta name="author" content="{% block page-author %}Krishna bhakta{% endblock %}">
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
	<link href="{% static "css/layout.css" %}" rel="stylesheet">
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.js"></script>
	<script type="text/javascript">
		jQuery.ajaxSettings.traditional = true; // убираем скобочки в конце имени массива в GET
	</script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

	{% block headscripts %}
	{% endblock %}
</head>

<body>
<div align="center">
	<img src="{% static "img/top.png" %}" style="max-width: 100%;max-height: 100%" />
</div>
<div id="layout">
	<div class="navbar navbar-default container" id="navbar" role="navigation">
		<div class="navbar-inner">
			<a class="navbar-brand" href="/">Krishna33</a>
			<ul class="nav navbar-nav">
				<!-- <li><a href="/">На главную</a></li> -->
				
				<li><a href="{% url 'events:list' %}">События</a></li>
				<li><a href="{% url 'posts:list' %}">Посты</a></li>
				{% if user.is_authenticated %}
				<li><a href="https://www.dropbox.com/sh/98l2fl97mnmzzcn/nzwYGQpyLr" target="_blank">Материалы</a></li>
				{% endif %}
                <li><a href="/store/">Магазин</a></li>
                <li><a href="/stream/">Трансляции</a></li>
                <li><a href="{% url 'contact' %}">Контакты</a></li>
				<li><a href="/accounts/login/">Вход</a></li>
				{% if user.is_staff %}
				<li><a href="/admin/">Админка</a></li>
				{% endif %}
			</ul>
			<!-- <a href="#" class="nav navbar-nav navbar-right">{% now "d" %}<br>{% now "b" %}</a> -->
		</div>
	</div>
	<div id="header" style="padding:0px;">{% block header %}{% endblock %}</div>
	<div class="container">
		<div class="row">
			<div id="content" class="col-md-12">{% block content %}{% endblock %}</div>
			<!-- <div id="sidebar" class="well col-md-3">{% block sidebar %}{% endblock %}</div> -->
		</div>
	</div>
	<div id="footer">{% block footer %}{% endblock %}</div>
</div>
  	<script type="text/javascript" src="{% static "js/ajax-csrf.js" %}" defer></script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-40774777-2', 'krishna33.ru');
        ga('send', 'pageview');
    </script>
    {% block footscripts %}
    {% endblock %}
</body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}
<h1 align="center">Вы можете связаться с нами:</h1>
<h3>
    <table align="center" cellpadding="5">
        <tr>
            <td><img src="{{ STATIC_URL }}img/tel.png" /></td>
            <td>+7 (904) 651-17-98</td>
        </tr>
        <tr>
            <td><img src="{{ STATIC_URL }}img/ICQ.png" /></td>
            <td>432443992
        </tr>
        <tr>
            <td><img src="{{ STATIC_URL }}img/email.png" /></td>
            <td>krsna33@yandex.ru</td>
        </tr>
        <tr>
            <td><a href="http://vk.com/mrooskv"><img src="{{ STATIC_URL }}img/vk.png" /></td>
            <td><a href="http://vk.com/mrooskv">vkontakte</a></td>
        </tr>
    </table>
</h3>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block headscripts %}
<meta name='wmail-verification' content='2505aebf7165bce1' />
{% endblock %}
{% block content %}
<div align="center">
<i>Сайт находится в разработке</i>
</div>
{% for post in posts %}
    {% include "posts/post-short.html" with post=post %}
{% empty %}
    <div align="center">Новостей пока нет!</div>
{% endfor %}
{% endblock %}